import type { AccountRole } from '@/lib/auth/roles';
import type { InteractiveMessagePayload } from '@/lib/whatsapp/interactive';

export type {
  InteractiveMessagePayload,
  InteractiveButtonsPayload,
  InteractiveListPayload,
  InteractiveButton,
  InteractiveListRow,
  InteractiveListSection,
} from '@/lib/whatsapp/interactive';

export interface Profile {
  id: string;
  user_id: string;
  full_name: string;
  email: string;
  avatar_url?: string;
  /**
   * Legacy free-form role column from migration 001. Never read
   * by the app since 017_account_sharing.sql introduced the typed
   * `account_role` enum. Flagged for removal in a later cleanup
   * migration — kept on the type so existing destructures don't
   * break.
   */
  role: string;
  /**
   * Opted-in beta feature keys for this account. The column survives
   * for future beta gates; no current feature reads it (Flows was
   * the last user and went to soft-GA in PR #134). Defaults to `[]`
   * for every profile; toggled per-account via a direct UPDATE on
   * the `profiles` row.
   */
  beta_features?: string[];
  /**
   * Account this profile is a member of. Added by
   * `017_account_sharing.sql`; NOT NULL in the DB post-backfill.
   * Optional on the type only because older serialised payloads
   * (cached client state, test fixtures) may not have it yet.
   */
  account_id?: string;
  /**
   * Caller's role within their account. Source of truth for every
   * role-gated UI / API check — call `hasMinRole` from
   * `@/lib/auth/roles` rather than comparing this string directly.
   */
  account_role?: AccountRole;
  created_at: string;
}

// ============================================================
// Account-sharing entities (017_account_sharing.sql)
// ============================================================

export interface Account {
  id: string;
  name: string;
  /** auth.users.id of the immutable owner. */
  owner_user_id: string;
  created_at: string;
  updated_at: string;
}

/**
 * Hydrated member row for the Settings → Members tab. Combines
 * the profile and its account_role for a single member of the
 * caller's account. Sensitive fields (email) are populated only
 * when the caller has admin+ — agents and viewers see name +
 * avatar + role only.
 */
export interface AccountMember {
  user_id: string;
  full_name: string;
  email: string | null;
  avatar_url: string | null;
  role: AccountRole;
  joined_at: string;
}

/**
 * Outstanding invite link row. `token_hash` is intentionally
 * absent — it lives only in the DB and on the server. The
 * plaintext token is returned once at creation time and surfaced
 * via the invite URL; never re-emitted.
 */
export interface AccountInvitation {
  id: string;
  account_id: string;
  /** Roles offered via invite — owner is never offered. */
  role: Exclude<AccountRole, 'owner'>;
  created_by_user_id: string | null;
  label: string | null;
  created_at: string;
  expires_at: string;
  accepted_at: string | null;
  accepted_by_user_id: string | null;
}

export interface Contact {
  id: string;
  user_id: string;
  account_id: string;
  phone: string;
  /** Digits-only form of `phone`, generated by the DB (migration 022)
   *  and unique per account. Read-only. */
  phone_normalized?: string;
  name?: string;
  preferred_name?: string | null;
  email?: string;
  company?: string;
  job_title?: string | null;
  /** Sensitive: never include in contact list payloads or application logs. */
  cpf?: string | null;
  cnpj?: string | null;
  whatsapp?: string | null;
  secondary_phone?: string | null;
  birth_day?: number | null;
  birth_month?: number | null;
  birth_year?: number | null;
  notes?: string | null;
  address_zip?: string | null;
  address_street?: string | null;
  address_number?: string | null;
  address_complement?: string | null;
  address_neighborhood?: string | null;
  address_city?: string | null;
  address_state?: string | null;
  address_country?: string | null;
  relationship_type?: ContactRelationshipType | null;
  source?: string | null;
  owner_user_id?: string | null;
  relationship_status?: ContactRelationshipStatus | null;
  first_contact_at?: string | null;
  last_contact_at?: string | null;
  next_follow_up_at?: string | null;
  archived_at?: string | null;
  deleted_at?: string | null;
  avatar_url?: string;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed `contact_tags(tags(*))` (e.g. the
   *  Inbox conversation list, for tag filtering). Absent otherwise. */
  tags?: Tag[];
  /**
   * For a lead contact: the client contact (itself referenced by
   * ad_accounts.contact_id) whose campaigns generated this lead — see
   * src/lib/traffic/attribution.ts. Null for client contacts
   * themselves and for leads with no resolvable attribution.
   */
  managed_by_contact_id?: string | null;
  attribution_source?: 'ctwa_referral' | 'personal_whatsapp_session' | null;
  attribution_platform?: 'meta' | 'google' | 'other' | null;
  attribution_campaign_id?: string | null;
  attribution_ad_set_id?: string | null;
  attribution_ad_id?: string | null;
  attribution_click_id?: string | null;
  attribution_headline?: string | null;
  attribution_source_url?: string | null;
  attributed_at?: string | null;
}

export type ContactRelationshipType =
  'client' | 'lead' | 'prospect' | 'partner' | 'supplier' | 'other';

export type ContactRelationshipStatus =
  'active' | 'inactive' | 'nurturing' | 'qualified' | 'unqualified';

export interface ContactEvent {
  id: string;
  account_id: string;
  contact_id: string | null;
  actor_user_id: string | null;
  event_type:
    | 'CONTACT_CREATED'
    | 'CONTACT_UPDATED'
    | 'CONTACT_DELETED'
    | 'CONTACT_RESTORED'
    | 'CONTACT_ARCHIVED'
    | 'CONTACT_TAG_ADDED'
    | 'CONTACT_TAG_REMOVED'
    | 'CONTACT_OWNER_CHANGED'
    | 'FOLLOWUP_CREATED'
    | 'MESSAGE_SENT'
    | 'MESSAGE_RECEIVED';
  metadata: Record<string, unknown>;
  occurred_at: string;
}

export interface ContactReminder {
  id: string;
  account_id: string;
  contact_id: string;
  user_id: string;
  title: string;
  remind_at: string;
  completed_at?: string | null;
  notified_at?: string | null;
  created_at: string;
}

export interface UpcomingContactBirthday {
  id: string;
  name?: string | null;
  preferred_name?: string | null;
  company?: string | null;
  phone: string;
  birth_day: number;
  birth_month: number;
  birth_year?: number | null;
  next_birthday: string;
  days_until: number;
}

export interface Tag {
  id: string;
  user_id: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContactTag {
  id: string;
  contact_id: string;
  tag_id: string;
}

export interface CustomField {
  id: string;
  user_id: string;
  /** Tenancy key — NOT NULL since migration 017. */
  account_id: string;
  field_name: string;
  field_type: string;
  field_options?: Record<string, unknown>;
  created_at: string;
}

export interface ContactCustomValue {
  id: string;
  contact_id: string;
  custom_field_id: string;
  value?: string;
}

export interface ContactNote {
  id: string;
  contact_id: string;
  user_id: string;
  note_text: string;
  created_at: string;
}

export interface ConversationNote {
  id: string;
  conversation_id: string;
  user_id: string;
  note_text: string;
  created_at: string;
}

export type ConversationStatus = 'open' | 'pending' | 'closed';

/**
 * Which transport this conversation's messages flow through.
 * `meta_cloud_api` — the official WhatsApp Business Cloud API (the
 * only channel that existed before migration 045).
 * `whatsapp_personal` — a personal WhatsApp account connected via QR
 * code (unofficial, Baileys-based — see docs/adr/0005). A contact can
 * have one conversation per channel (migration 045 widened the
 * uniqueness from (account,contact) to (account,contact,channel)).
 */
export type WhatsAppChannel = 'meta_cloud_api' | 'whatsapp_personal';

export interface Conversation {
  id: string;
  user_id: string;
  contact_id: string;
  status: ConversationStatus;
  channel: WhatsAppChannel;
  whatsapp_personal_session_id?: string | null;
  whatsapp_remote_jid?: string | null;
  personal_session?: {
    id: string;
    label?: string | null;
    phone_number?: string | null;
  } | null;
  assigned_agent_id?: string;
  last_message_text?: string;
  last_message_at?: string;
  last_message_direction?: SenderType | null;
  awaiting_reply?: boolean;
  waiting_since?: string | null;
  last_customer_message_at?: string | null;
  last_team_reply_at?: string | null;
  unread_count: number;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  /**
   * AI auto-reply state for this thread (migration 029 + 033):
   *  - `ai_autoreply_disabled` — the bot is paused here (a human took
   *    over, or the model handed off). Sticky until re-enabled.
   *  - `ai_reply_count` — how many times the bot has auto-replied,
   *    checked against the account's per-conversation cap.
   *  - `ai_handoff_summary` — short internal note the bot wrote when it
   *    handed off, shown to whoever takes the thread over.
   */
  ai_autoreply_disabled?: boolean;
  ai_reply_count?: number;
  ai_handoff_summary?: string | null;
}

// ============================================================
// Notifications (migration 027)
// ============================================================

export type NotificationType =
  | 'conversation_assigned'
  | 'contact_birthday'
  | 'contact_reminder'
  | 'conversation_message'
  | 'conversation_overdue';

export interface Notification {
  id: string;
  account_id: string;
  /** Recipient — the agent this notification is for. */
  user_id: string;
  type: NotificationType;
  conversation_id?: string;
  contact_id?: string;
  /** Who triggered it. Null when an automation/system assigned it. */
  actor_user_id?: string;
  title: string;
  body?: string;
  action_url?: string | null;
  metadata?: Record<string, unknown>;
  dedupe_key?: string | null;
  read_at?: string;
  created_at: string;
}

export type SenderType = 'customer' | 'agent' | 'bot';
export type ContentType =
  | 'text'
  | 'image'
  | 'document'
  | 'audio'
  | 'video'
  | 'location'
  | 'template'
  /** Customer tapped a reply button or list row on a message we sent. */
  | 'interactive';
export type MessageStatus =
  | 'pending'
  | 'queued'
  | 'sending'
  | 'sent'
  | 'delivered'
  | 'read'
  | 'replied'
  | 'failed'
  | 'cancelled';

export interface Message {
  id: string;
  conversation_id: string;
  sender_type: SenderType;
  sender_id?: string;
  content_type: ContentType;
  content_text?: string;
  media_url?: string;
  template_name?: string;
  message_id?: string;
  status: MessageStatus;
  /** Transport used for this outbound attempt. */
  provider?: 'meta_cloud_api' | 'whatsapp_personal' | string;
  provider_status?: string;
  provider_http_status?: number;
  error_code?: string;
  error_message?: string;
  attempt_count?: number;
  queued_at?: string;
  sending_at?: string;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  failed_at?: string;
  cancelled_at?: string;
  last_attempt_at?: string;
  created_at: string;
  reply_to_message_id?: string;
  /**
   * Only set when `content_type === 'interactive'` — the stable id of
   * the button or list row the customer tapped. The Flows engine uses
   * this to route the next node; the inbox bubble uses it as a styling
   * cue (renders with a "↩ button reply" affordance).
   */
  interactive_reply_id?: string;
  /**
   * Structured payload of an OUTBOUND interactive message (reply
   * buttons or list) we sent. Lets the thread re-render the buttons /
   * rows, not just the body text. Only set when `content_type ===
   * 'interactive'` and `sender_type` is agent/bot. Migration 035.
   */
  interactive_payload?: InteractiveMessagePayload;
  /**
   * True when the AI auto-reply bot generated + sent this message (as
   * opposed to a human agent or a deterministic Flow/automation send,
   * which all share `sender_type='bot'`/`'agent'`). Drives the "AI"
   * badge in the inbox. Migration 033.
   */
  ai_generated?: boolean;
  /**
   * Set when an agent corrects a typo/mistake after sending (migration
   * 046). On the whatsapp_personal channel this reflects a REAL
   * WhatsApp edit (via Baileys); on meta_cloud_api it's a CRM-only
   * correction — Meta's Cloud API has no message-edit endpoint, so the
   * customer's copy is unchanged. The UI must not conflate the two.
   */
  edited_at?: string;
}

export type ReactionActor = 'customer' | 'agent';

export interface MessageReaction {
  id: string;
  message_id: string;
  conversation_id: string;
  actor_type: ReactionActor;
  actor_id?: string;
  emoji: string;
  created_at: string;
}

export interface WhatsAppConfig {
  id: string;
  user_id: string;
  phone_number_id: string;
  waba_id?: string;
  access_token: string;
  verify_token?: string;
  status: 'connected' | 'disconnected';
  connected_at?: string;
  /**
   * Set when POST /{phone_number_id}/register last succeeded. NULL
   * means the number was saved but never actually subscribed for
   * webhooks on Meta's side — inbound events will be silently lost.
   */
  registered_at?: string;
  /** Set when POST /{waba_id}/subscribed_apps last succeeded. */
  subscribed_apps_at?: string;
  /** Last error from /register; cleared on success. */
  last_registration_error?: string;
}

// ============================================================
// Personal WhatsApp (QR code, unofficial) — migration 045
// ============================================================

export type WhatsAppPersonalStatus =
  'disconnected' | 'connecting' | 'qr_pending' | 'connected' | 'error';

export type WhatsAppPersonalHistorySyncStatus =
  'idle' | 'pending' | 'syncing' | 'completed' | 'paused' | 'error';

export interface WhatsAppPersonalSession {
  id: string;
  account_id: string;
  user_id: string;
  status: WhatsAppPersonalStatus;
  phone_number?: string;
  last_error?: string;
  connected_at?: string;
  history_sync_status?: WhatsAppPersonalHistorySyncStatus;
  history_sync_progress?: number;
  history_sync_chats?: number;
  history_sync_messages?: number;
  history_sync_error?: string;
  /**
   * Traffic module client (contacts.id) this connection is dedicated
   * to, if any — set in Settings so a lead landing here without a
   * resolvable ad referral is still attributed to the right client
   * (see src/lib/traffic/attribution.ts). Null for connections not
   * tied to one specific client's campaigns.
   */
  client_contact_id?: string | null;
  created_at: string;
  updated_at: string;
}

// Raw Meta status enum. We persist this verbatim from Meta (sync + webhook)
// rather than collapsing to a local TitleCase set — distinctions like
// PAUSED vs DISABLED vs IN_APPEAL drive the edit/resubmit/delete flows.
// DRAFT is the local-only state before the row is submitted to Meta.
export type MessageTemplateStatus =
  | 'DRAFT'
  | 'PENDING'
  | 'APPROVED'
  | 'REJECTED'
  | 'PAUSED'
  | 'DISABLED'
  | 'IN_APPEAL'
  | 'PENDING_DELETION';

export type TemplateButton =
  | { type: 'QUICK_REPLY'; text: string }
  | { type: 'URL'; text: string; url: string; example?: string }
  | { type: 'PHONE_NUMBER'; text: string; phone_number: string }
  | { type: 'COPY_CODE'; text: string; example: string };

export interface TemplateSampleValues {
  body?: string[];
  header?: string[];
}

export interface MessageTemplate {
  id: string;
  user_id: string;
  name: string;
  category: 'Marketing' | 'Utility' | 'Authentication';
  language?: string;
  header_type?: 'text' | 'image' | 'video' | 'document';
  header_content?: string;
  header_handle?: string;
  header_media_url?: string;
  body_text: string;
  footer_text?: string;
  buttons?: TemplateButton[];
  sample_values?: TemplateSampleValues;
  status?: MessageTemplateStatus;
  meta_template_id?: string;
  rejection_reason?: string;
  quality_score?: 'GREEN' | 'YELLOW' | 'RED';
  submission_error?: string;
  last_submitted_at?: string;
  created_at: string;
}

export interface Pipeline {
  id: string;
  user_id: string;
  name: string;
  created_at: string;
}

export interface PipelineStage {
  id: string;
  pipeline_id: string;
  name: string;
  position: number;
  color: string;
  created_at: string;
}

export type DealStatus = 'open' | 'won' | 'lost';

export interface Deal {
  id: string;
  user_id: string;
  pipeline_id: string;
  stage_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved.
   */
  contact_id: string | null;
  conversation_id?: string | null;
  assigned_to?: string;
  title: string;
  value: number;
  currency?: string;
  notes?: string;
  expected_close_date?: string;
  status?: DealStatus;
  created_at: string;
  updated_at?: string;
  contact?: Contact;
  stage?: PipelineStage;
  assignee?: Profile;
  tags?: Tag[];
  conversation?: Pick<
    Conversation,
    | 'id'
    | 'channel'
    | 'status'
    | 'last_message_text'
    | 'last_message_at'
    | 'last_message_direction'
    | 'unread_count'
    | 'awaiting_reply'
    | 'waiting_since'
    | 'last_customer_message_at'
    | 'last_team_reply_at'
  > | null;
}

export interface PipelineReplySettings {
  newMinutes: number;
  attentionMinutes: number;
  overdueMinutes: number;
  messageNotifications: boolean;
}

export type BroadcastStatus =
  'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
export type RecipientStatus =
  'pending' | 'sent' | 'delivered' | 'read' | 'replied' | 'failed';

export interface Broadcast {
  id: string;
  user_id: string;
  name: string;
  template_name: string;
  template_language: string;
  template_variables?: Record<string, unknown>;
  audience_filter?: Record<string, unknown>;
  scheduled_at?: string;
  status: BroadcastStatus;
  total_recipients: number;
  sent_count: number;
  delivered_count: number;
  read_count: number;
  replied_count: number;
  failed_count: number;
  created_at: string;
}

export interface BroadcastRecipient {
  id: string;
  broadcast_id: string;
  /**
   * Nullable after migration 004 — becomes NULL when the referenced
   * contact is deleted (ON DELETE SET NULL). History preserved; the
   * UI renders "Unknown" for orphaned rows.
   */
  contact_id: string | null;
  status: RecipientStatus;
  sent_at?: string;
  delivered_at?: string;
  read_at?: string;
  replied_at?: string;
  error_message?: string;
  /**
   * Meta's message id, persisted when the broadcast send succeeds so
   * the webhook can mirror status updates back onto the recipient row.
   * Added in migration 003.
   */
  whatsapp_message_id?: string;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Automations (migration 006)
// ============================================================

export type AutomationTriggerType =
  | 'new_message_received'
  | 'first_inbound_message'
  | 'keyword_match'
  | 'new_contact_created'
  | 'conversation_assigned'
  | 'tag_added'
  | 'time_based'
  /** Customer tapped a reply button / list row whose id matches; lets
   *  multi-step menus be chained across automations. */
  | 'interactive_reply';

export type AutomationStepType =
  | 'sales_qualify'
  | 'send_message'
  | 'send_buttons'
  | 'send_list'
  | 'send_template'
  | 'add_tag'
  | 'remove_tag'
  | 'assign_conversation'
  | 'update_contact_field'
  | 'create_deal'
  | 'wait'
  | 'condition'
  | 'send_webhook'
  | 'close_conversation';

export type AutomationLogStatus = 'success' | 'partial' | 'failed';

export interface KeywordMatchTriggerConfig {
  keywords: string[];
  /**
   * `contains` (the default) is a raw substring test, so a short keyword
   * matches inside longer words — "k" fires on "thanks". `word` is the
   * boundary-aware alternative added for issue #409; see
   * `matchesWholeWord` in `@/lib/automations/engine` for its exact
   * semantics. Flows carry their own keyword config and stay
   * substring-only (`@/lib/flows/types`).
   */
  match_type: 'exact' | 'contains' | 'word';
  case_sensitive?: boolean;
}

export interface TagTriggerConfig {
  tag_id: string;
}

export interface TimeBasedTriggerConfig {
  /** Cron expression or simple HH:mm string; engine can accept either. */
  schedule: string;
  timezone?: string;
}

export interface InteractiveReplyTriggerConfig {
  /** Button / list-row ids to match, exact. Any one matching fires. */
  reply_ids: string[];
}

export type AutomationTriggerConfig =
  | Record<string, never>
  | KeywordMatchTriggerConfig
  | TagTriggerConfig
  | TimeBasedTriggerConfig
  | InteractiveReplyTriggerConfig
  | Record<string, unknown>;

export interface SendMessageStepConfig {
  text: string;
}

export interface SalesQualifyStepConfig {
  mode: 'suggestion';
}

/**
 * `send_buttons` / `send_list` step configs carry the full interactive
 * payload (same shape stored on messages + quick replies). `kind` is
 * implied by the step_type but kept on the payload for a uniform shape.
 */
export type SendButtonsStepConfig = InteractiveMessagePayload;
export type SendListStepConfig = InteractiveMessagePayload;

export interface SendTemplateStepConfig {
  template_name: string;
  language?: string;
  variables?: Record<string, string>;
}

export interface TagStepConfig {
  tag_id: string;
}

export interface AssignConversationStepConfig {
  mode: 'specific' | 'round_robin';
  agent_id?: string;
}

export interface UpdateContactFieldStepConfig {
  /**
   * Either a built-in contact column (`name` | `email` | `company`) or a
   * custom field encoded as `custom:<custom_field_id>`. The `custom:` prefix
   * is how the engine distinguishes a `contact_custom_values` write from a
   * direct `contacts` column update. Older configs store the bare column name,
   * so this stays backward compatible.
   */
  field: string;
  /** Supports `{{ vars.* }}` / `{{ message.text }}` interpolation at runtime. */
  value: string;
}

export interface CreateDealStepConfig {
  pipeline_id: string;
  stage_id: string;
  title: string;
  value?: number;
}

export interface WaitStepConfig {
  amount: number;
  unit: 'minutes' | 'hours' | 'days';
}

export type ConditionSubject =
  'contact_field' | 'tag_presence' | 'message_content' | 'time_of_day';

export interface ConditionStepConfig {
  subject: ConditionSubject;
  /** e.g. field name, tag id, substring, or "HH:mm-HH:mm" depending on subject */
  operand?: string;
  /** For contact_field equals / message_content contains — comparison value */
  value?: string;
}

export interface SendWebhookStepConfig {
  url: string;
  headers?: Record<string, string>;
  body_template?: string;
}

export type AutomationStepConfig =
  | SalesQualifyStepConfig
  | SendMessageStepConfig
  | SendButtonsStepConfig
  | SendListStepConfig
  | SendTemplateStepConfig
  | TagStepConfig
  | AssignConversationStepConfig
  | UpdateContactFieldStepConfig
  | CreateDealStepConfig
  | WaitStepConfig
  | ConditionStepConfig
  | SendWebhookStepConfig
  | Record<string, never>
  | Record<string, unknown>;

export interface Automation {
  id: string;
  /** Account tenancy key — every automation belongs to one account
   *  (migration 017 made the column NOT NULL). The engine looks up
   *  active automations by this field on inbound webhook events. */
  account_id: string;
  /** Original author. Used for log audit + outbound message
   *  sender-of-record, never for tenancy isolation. */
  user_id: string;
  name: string;
  description?: string;
  trigger_type: AutomationTriggerType;
  trigger_config: AutomationTriggerConfig;
  is_active: boolean;
  execution_count: number;
  last_executed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutomationStep {
  id: string;
  automation_id: string;
  parent_step_id?: string | null;
  branch?: 'yes' | 'no' | null;
  step_type: AutomationStepType;
  step_config: AutomationStepConfig;
  position: number;
  created_at: string;
}

export interface AutomationLogStepResult {
  step_id: string;
  step_type: AutomationStepType;
  status: 'success' | 'skipped' | 'failed';
  detail?: string;
}

export interface AutomationLog {
  id: string;
  automation_id: string;
  user_id: string;
  contact_id: string | null;
  trigger_event: string;
  steps_executed: AutomationLogStepResult[];
  status: AutomationLogStatus;
  error_message?: string | null;
  created_at: string;
  contact?: Contact;
}

// ============================================================
// Quick replies — reusable snippets (migration 035)
// ============================================================

export type QuickReplyKind = 'text' | 'interactive';

export interface QuickReply {
  id: string;
  /** Account tenancy key — shared across all members of the account. */
  account_id: string;
  /** Author / audit only. */
  user_id: string;
  title: string;
  kind: QuickReplyKind;
  /** Set when `kind === 'text'`. */
  content_text?: string | null;
  /** Set when `kind === 'interactive'`. */
  interactive_payload?: InteractiveMessagePayload | null;
  created_at: string;
  updated_at: string;
}

// ============================================================
// Content & social media (migration 042) — social_profiles,
// content_posts, content_post_targets. A "client" here is an
// existing Contact; no separate client entity was introduced.
// ============================================================

export type SocialPlatform = 'instagram' | 'facebook' | 'linkedin';
export type SocialConnectionStatus = 'not_connected' | 'connected' | 'error';

export interface SocialProfile {
  id: string;
  account_id: string;
  contact_id: string;
  user_id: string;
  platform: SocialPlatform;
  handle: string;
  display_name?: string | null;
  connection_status: SocialConnectionStatus;
  external_account_id?: string | null;
  /** AES-256-GCM ciphertext (src/lib/whatsapp/encryption.ts). Never
   *  decrypted client-side — omitted from any client-facing select. */
  access_token_encrypted?: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed contacts(*) (e.g. the social
   *  profiles list grouped by client). Absent otherwise. */
  contact?: Contact;
}

/** Distinct from the WhatsApp-message `ContentType` above — this is the
 *  kind of social-media post being created, not an inbound/outbound
 *  message's payload type. */
export type PostContentType =
  'image' | 'video' | 'carousel' | 'text' | 'story' | 'reel';

export type ContentPostStatus =
  | 'draft'
  | 'pending_approval'
  | 'approved'
  | 'scheduled'
  | 'publishing'
  | 'published'
  | 'failed'
  | 'cancelled';

export interface ContentMediaItem {
  url: string;
  path: string;
  kind: 'image' | 'video';
  position: number;
}

export interface ContentPost {
  id: string;
  account_id: string;
  contact_id: string;
  created_by: string;
  content_type: PostContentType;
  caption?: string | null;
  hashtags: string[];
  media: ContentMediaItem[];
  link_url?: string | null;
  cta?: string | null;
  status: ContentPostStatus;
  scheduled_at?: string | null;
  published_at?: string | null;
  approved_by?: string | null;
  approved_at?: string | null;
  error_message?: string | null;
  created_at: string;
  updated_at: string;
  /** Hydrated by queries that embed contacts(*) / content_post_targets(*). */
  contact?: Contact;
  targets?: ContentPostTarget[];
}

export type ContentPostTargetStatus =
  'pending' | 'publishing' | 'published' | 'failed';

export interface ContentPostTarget {
  id: string;
  post_id: string;
  social_profile_id: string;
  status: ContentPostTargetStatus;
  external_post_id?: string | null;
  error_code?: string | null;
  error_message?: string | null;
  attempted_at?: string | null;
  published_at?: string | null;
  created_at: string;
  /** Hydrated by queries that embed social_profiles(*). */
  social_profile?: SocialProfile;
}

export type ContentReferenceStatus =
  'idea' | 'analyze' | 'reference' | 'created' | 'archived';

export interface ContentReference {
  id: string;
  account_id: string;
  contact_id?: string | null;
  created_by: string;
  source_url: string;
  platform: string;
  title: string;
  description?: string | null;
  thumbnail_url?: string | null;
  author?: string | null;
  published_at?: string | null;
  public_text?: string | null;
  category?: string | null;
  topic?: string | null;
  content_format?: string | null;
  notes?: string | null;
  status: ContentReferenceStatus;
  is_favorite: boolean;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  contact?: Pick<Contact, 'id' | 'name'> | null;
  reference_tags?: Array<{ tag: ContentTag }>;
  reference_collections?: Array<{ collection: ContentCollection }>;
}

export interface ContentCollection {
  id: string;
  account_id: string;
  created_by: string;
  name: string;
  description?: string | null;
  color: string;
  created_at: string;
  updated_at: string;
}

export interface ContentTag {
  id: string;
  account_id: string;
  created_by: string;
  name: string;
  color: string;
  created_at: string;
}

export interface ContentIdea {
  id: string;
  account_id: string;
  contact_id?: string | null;
  created_by: string;
  body: string;
  source_url?: string | null;
  asset_url?: string | null;
  kind: 'text' | 'url' | 'image' | 'note' | 'reference';
  status: 'inbox' | 'organized' | 'archived';
  reference_id?: string | null;
  created_at: string;
  updated_at: string;
  contact?: Pick<Contact, 'id' | 'name'> | null;
}

// ============================================================
// Traffic & Performance (migration 044) — ad_accounts, ad_campaigns,
// ad_sets, ads, landing_pages, traffic_metrics_daily,
// traffic_recommendations, traffic_optimization_tasks,
// traffic_optimization_log. "Client" is a Contact, same decision as
// the Content module. The commercial funnel (Lead -> ... -> Venda) is
// NOT modeled here — it's `deals` moving through `pipeline_stages`.
// ============================================================

export type AdPlatform = 'meta' | 'google' | 'other';
export type AdConnectionStatus = 'not_connected' | 'connected' | 'error';

export interface AdAccount {
  id: string;
  account_id: string;
  contact_id: string;
  user_id: string;
  platform: AdPlatform;
  name: string;
  connection_status: AdConnectionStatus;
  external_account_id?: string | null;
  /** AES-256-GCM ciphertext — never decrypted client-side. */
  access_token_encrypted?: string | null;
  currency: string;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
  contact?: Contact;
}

export type AdEntityStatus = 'active' | 'paused' | 'ended' | 'draft';

export interface AdCampaign {
  id: string;
  ad_account_id: string;
  external_id?: string | null;
  name: string;
  objective?: string | null;
  status: AdEntityStatus;
  budget?: number | null;
  budget_type?: 'daily' | 'lifetime' | null;
  currency: string;
  start_date?: string | null;
  end_date?: string | null;
  created_at: string;
  updated_at: string;
  ad_account?: AdAccount;
}

export interface AdSet {
  id: string;
  campaign_id: string;
  external_id?: string | null;
  name: string;
  targeting_summary?: string | null;
  budget?: number | null;
  status: AdEntityStatus;
  created_at: string;
  updated_at: string;
  campaign?: AdCampaign;
}

export interface Ad {
  id: string;
  ad_set_id: string;
  external_id?: string | null;
  name: string;
  headline?: string | null;
  body?: string | null;
  media_url?: string | null;
  thumbnail_url?: string | null;
  cta?: string | null;
  landing_page_id?: string | null;
  status: AdEntityStatus;
  /** Feeds "days active" in the deterministic creative-fatigue score. */
  launched_at?: string | null;
  created_at: string;
  updated_at: string;
  ad_set?: AdSet;
}

export interface LandingPage {
  id: string;
  account_id: string;
  contact_id: string;
  name: string;
  url: string;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  contact?: Contact;
}

export type TrafficEntityType =
  'ad_account' | 'campaign' | 'ad_set' | 'ad' | 'landing_page';
export type TrafficMetricsSource = 'manual' | 'csv_import' | 'api';

export interface TrafficMetricsDaily {
  id: string;
  account_id: string;
  entity_type: TrafficEntityType;
  entity_id: string;
  date: string;
  impressions: number;
  reach: number;
  clicks: number;
  spend: number;
  leads: number;
  conversions: number;
  revenue: number;
  visits: number;
  source: TrafficMetricsSource;
  created_by?: string | null;
  created_at: string;
}

export type RecommendationEntityType = TrafficEntityType | 'funnel';
export type RecommendationCategory =
  'creative_fatigue' | 'landing_page' | 'funnel' | 'budget' | 'alert';
export type RecommendationPriority = 'critical' | 'high' | 'medium' | 'low';
export type RecommendationStatus =
  'new' | 'in_review' | 'approved' | 'in_progress' | 'done' | 'dismissed';

export interface TrafficRecommendation {
  id: string;
  account_id: string;
  contact_id: string;
  entity_type?: RecommendationEntityType | null;
  entity_id?: string | null;
  category: RecommendationCategory;
  priority: RecommendationPriority;
  status: RecommendationStatus;
  problem: string;
  diagnosis: string;
  recommended_action: string;
  expected_impact?: string | null;
  ai_raw?: Record<string, unknown> | null;
  created_at: string;
  updated_at: string;
  contact?: Contact;
}

export type OptimizationTaskStatus =
  'todo' | 'in_progress' | 'done' | 'cancelled';

export interface TrafficOptimizationTask {
  id: string;
  account_id: string;
  contact_id: string;
  recommendation_id?: string | null;
  title: string;
  responsible?: string | null;
  due_date?: string | null;
  priority: RecommendationPriority;
  status: OptimizationTaskStatus;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  contact?: Contact;
  recommendation?: TrafficRecommendation;
}

export interface TrafficOptimizationLogEntry {
  id: string;
  account_id: string;
  contact_id: string;
  task_id?: string | null;
  recommendation_id?: string | null;
  event: string;
  detail?: string | null;
  actor?: string | null;
  created_at: string;
}

export type SalesTaskType = 'task' | 'call' | 'meeting' | 'follow_up';
export type SalesTaskStatus = 'todo' | 'in_progress' | 'done' | 'cancelled';
export type SalesTaskPriority = 'low' | 'medium' | 'high' | 'urgent';

export interface SalesTask {
  id: string;
  account_id: string;
  title: string;
  description?: string | null;
  task_type: SalesTaskType;
  status: SalesTaskStatus;
  priority: SalesTaskPriority;
  due_at?: string | null;
  completed_at?: string | null;
  contact_id?: string | null;
  deal_id?: string | null;
  assigned_to: string;
  created_by: string;
  created_at: string;
  updated_at: string;
}
